//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P208_ASP_Front.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlstarEntities : DbContext
    {
        public AlstarEntities()
            : base("name=AlstarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Parallax> Parallaxes { get; set; }
        public virtual DbSet<AdminSetting> AdminSettings { get; set; }
    }
}
